### ISSUE TITLE
install-jogl.sh fix (replace w/ new zulu version - readme & script)

### ISSUE THREAD

**Issue by quangmng** [Birch-san/arm-editor-launcher#5]
There is a version of zulu available (this version on your readme & script does not exist?)
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/57740309/169995946-d701d3a2-13ac-436f-89de-3efff21e8b18.png">
<img width="1840" alt="Screen Shot 2022-05-24 at 19 08 37" src="https://user-images.githubusercontent.com/57740309/169995238-679e6b60-5983-4c47-9dfb-cabaf456a839.png">
No wonder why my artifacts were not installed properly...

**Comment by Birch-san** [comment]
the help text prints an _**Example** invocation_.  
I can't know what JDK version you downloaded or where you extracted it to. You should download the latest available.  
what would you suggest I write there instead? it's a moving target

**Comment by quangmng** [comment]
Firstly, what do you mean by "the help text"? (probs the comment part when command ran incorrectly/missing args.)
Secondly, when you provide a placeholder, showing the path of zulu, don't put the part I highlighted earlier in my screenshot above in your **Readme.md** because that will confuse people.
<img width="889" alt="image" src="https://user-images.githubusercontent.com/57740309/170001024-d8d50802-f562-479c-ad47-5c27059e522b.png">
Just do "*latest-zulu-version*" or something similar, up to you.

P.s.: Did I miss something here as well?
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/57740309/170001231-fe2c3e9a-d3b9-4763-977f-c3de126fe525.png">

**Comment by Birch-san** [comment]
> what do you mean by "the help text"?

the function `print_help` you included in your screenshot.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/6141784/170139450-f23d2985-0b63-4a9b-b4d9-861cf1b96507.png">

> when you provide a placeholder, showing the path of zulu, don't put the part I highlighted earlier in my screenshot above in your Readme.md because that will confuse people

I've now changed the README to recommend renaming the folder so that the examples have a common standard filepath to work against.  
I've also updated every `JAVA_HOME` example to explain that the folder path is indicative only.

> Did I miss something here as well?

ah, you didn't miss anything. looks like it doesn't work with an empty Maven registry.

I've pushed a change to make it work better with clean install. I've also updated `launcher.sh` to work with the new license bridge server.

**Comment by quangmng** [comment]
Alright, I've used your new update and compiled the launcher. The maven install & jogl worked until this happened... (Ran both configurations. 1st one as-is, i.e. BridgeServer x86_64 and Unofficial Launcher aarch64).
![image](https://user-images.githubusercontent.com/57740309/170237140-9bbbd968-a663-4453-b22f-cf4b2a72035e.png)

**Comment by Birch-san** [comment]
ah, yeah, license-bridge-server is special because it needs to be built & run with an entirely different JDK:  
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/6141784/170238182-4322cb16-861e-4fb2-9a02-36888de9577d.png">
you'll need to download JDK8 (you can grab from the same Azul download page), and configure just `license-bridge-server` to be built with it.  
_for **building** license-bridge-server, you can technically use native aarch64 JDK8, but best to download x86_64 JDK8 if you want to be able to **run** any run configurations related to license-bridge-server._

all other projects can be built with the Project JDK (aarch64 FX JDK17).
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/6141784/170238260-df6182e1-86ef-47ed-b468-8e848264729d.png">

this change escaped because it's not something that I can share via version control (it's local IntelliJ workspace config).

**Comment by Birch-san** [comment]
you may find it helpful uncheck "Use compiler from module target SDK" in settings:  
<img width="730" alt="image" src="https://user-images.githubusercontent.com/6141784/170240170-00b0031f-8f2d-48d7-97f6-1367fe6a3184.png">

otherwise, you'll find that license-bridge-server's Module SDK gets reset to the Project SDK every time you do a Maven Import.

**Comment by quangmng** [comment]
Thanks for the fix, L2D is launched w/ the licence server running now. 
Also just a quick question, will an activated L2D license work or it will default to a trial license?

**Comment by Birch-san** [comment]
brilliant! glad it's working.
In theory an activated L2D license _could_ work, but I haven't tried it.
